export const allowedEmails = [
  "rupamdholakiya@gmail.com",
  "rupamdholakiya023@gmail.com",
  "jdholakiya04@gmail.com",
  "info@harshubh.com",
  "class@harshubh.com",
  "sheikhzeeshan07@gmail.com",
  "Harshubh@gmail.com",
  


  // 10/07/2026 09/07/27"
  "astro@harshubh.com",
  "roopaammanagi@gmail.com",
  "ojesvikumarmadaan@gmail.com",
  "drsingh.male@gmail.com",
  "onkarsathe939@gmail.com",
  "somil29@gmail.com",
  "harshmehtaadv@gmail.com",
  "meethgohil28@gmail.com",
  "mastermindsanyam@gmail.com",
  "maniguglani.13@gmail.com",
  "harishverma.ac.in@gmail.com",
  "mayankpatel607@gmail.com",
  "hanrahul40@gmail.com",
  "siyodiabhavesh@gmail.com",
  "rakesh.gehlot02@gmail.com",
  "paraggaikwad@gmail.com",
  "coolswappy7@gmail.com",
  "angel.ganatra24@gmail.com",
  "parth.khalpada@gmail.com",
  "amolburade8788@gmail.com",
  "saurabhtiwari2491@gmail.com",
  "sa525301@gmail.com",
  "dnyandeob1511@gmail.com",
  "gajubmali@gmail.com",
  "bhupeshnarwani1979@gmail.com",
  "nariyaprince15@gmail.com",
  "caronak0708@gmail.com",
  "kulkarnisameer190776@gmail.com",
  "amansethmusic@gmail.com",
  "amitdhruve4@gmail.com",
  "abhays9096@gmail.com",
  "bobbyptanna@gmail.com",
];